sudo: required

services:
  - docker
  - mysql

# Handle git submodules yourself
git:
  submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - git submodule foreach --recursive git checkout $BRANCH
  - docker build -t agamblin/eh-client-test -f ./client/Dockerfile.dev ./client
  - docker build -t agamblin/eh-server-test -f ./server/Dockerfile.dev ./server
  - mysql -e 'CREATE DATABASE eh_testing;'

script:
  - docker run -e CI=true agamblin/eh-client-test yarn launch-tests-ci
  - docker run --net=host -e CI=true -e SQL_HOST=127.0.0.1 -e SQL_PORT=3306 -e SQL_USER=root -e SQL_PASSWORD='' -e SQL_DB=eh_testing -e NODE_ENV=CI -e JWT_SECRET=somejwtrandom agamblin/eh-server-test yarn launch-tests

after_success:
  - docker build -t agamblin/eh-client ./client
  - docker build -t agamblin/eh-server ./server
  - docker build -t agamblin/eh-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push agamblin/eh-client
  - docker push agamblin/eh-server
  - docker push agamblin/eh-nginx

deploy:
  - provider: elasticbeanstalk
    region: 'eu-west-3'
    app: 'eh'
    env: $AWS_EB_ENV
    bucket_name: $AWS_ENV_BUCKET_NAME
    bucket_path: $AWS_EB_ENV
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(master|develop)$
