sudo: required

services:
  - docker
  - mysql

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

# Handle git submodules yourself
git:
  submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - git submodule foreach --recursive git pull
  - git submodule foreach --recursive git checkout master
  - docker build -t agamblin/eh-client-test -f ./client/Dockerfile.dev ./client
  - docker build -t agamblin/eh-server-test -f ./server/Dockerfile.dev ./server
  - mysql -e 'CREATE DATABASE eh_testing;'

script:
  - docker run -e CI=true agamblin/eh-client-test yarn launch-tests-ci
  - docker run --net=host -e CI=true -e LOGGER=false -e SQL_HOST=127.0.0.1 -e SQL_PORT=3306 -e SQL_USER=root -e SQL_PASSWORD='' -e SQL_DB=eh_testing -e NODE_ENV=CI -e JWT_SECRET=somejwtrandom agamblin/eh-server-test yarn launch-tests

deploy:
  provider: script
  script: bash ./deployment/deploy.sh
  on:
    branch: master
