apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: esport-hatcher
build:
  local:
    push: false
  artifacts:
    - image: agamblin/eh-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - '**/*.ts'
          - '**/*.tsx'
          - '**/*.scss'
          - '**/*.css'
          - '**/*.html'
    - image: agamblin/eh-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - '**/*.js'
          - '**/*.ts'
deploy:
  kubectl:
    manifests:
      - k8s/manifests/*
