branch-defaults:
  develop:
    environment: EsportHatcherStaging-env
environment-defaults:
  EsportHatcherStaging-env:
    branch: null
    repository: null
global:
  application_name: esport-hatcher-staging
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-west-3::platform/Multi-container Docker
    running on 64bit Amazon Linux/2.15.0
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
