apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    component: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mysql
  template:
    metadata:
      labels:
        component: mysql
    spec:
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
      containers:
        - name: mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          command: ['/bin/sh']
          args: [
              '-c',
              "echo 'CREATE DATABASE IF NOT EXISTS eh; CREATE DATABASE IF NOT EXISTS eh_testing;' > /docker-entrypoint-initdb.d/init.sql;
              /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci",
            ]
          resources:
            limits:
              memory: '512Mi'
              cpu: '500m'
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
              subPath: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eh-secrets
                  key: SQL_PASSWORD
            - name: MYSQL_DATABASE
              value: eh
